dist: xenial
addons:
  apt:
    packages:
      - libgsl0ldbl
      - libgslcblas0
      - libgsl-dev
      - gsl-bin
      - libgsl0-dev
      - libmagick++-dev
before_install:
#  - sudo apt-get -qq update
#  - sudo apt-get install -y libgsl0ldbl
#  - sudo apt-get install libgsl0-dev
#  - sudo apt-get install gsl-bin
#  - sudo apt-get install libgsl0-dev
#  - sudo apt-get install libgsl-dev
language: r
r:
  - devel
r_packages:
  - diversitree
  - knitr
  - testthat
  - devtools
env:
  global:
    - R_CHECK_ARGS="--as-cran"
sudo: true
cache: packages
warnings_are_errors: false
